### ISSUE TITLE
Redirecting the Wishlist button to the new Wishlist

### ISSUE THREAD

**Issue by GyulizH** [GyulizH/ExtendedWishlist#6]
The button should direct to the extended wishlist page which will be a list filled with clothes only added to wishlist and clothes added in combination categories.

**Comment by kucukkanat** [comment]
Create a different script which will load only on `/wishlist` path in your `manifest.json` that will replace the current wishlist DOM element with ours.

**Comment by kucukkanat** [comment]
The button's behaviour should stay the same, only the structure of the wishlist page will be manipulated by the script mentioned in above comment
